config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root   'home#index'
  get    'signup'  => 'users#new'
  get    'edit'    => 'home#edit'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'preview' => "profiles#preview"
  resources :users 
  resources :profiles
  resources :educations
  resources :experiences
  resources :projects 
end

app/controllers/home_controller.rb
 class HomeController < ApplicationController

  def index
    logged_in_user
    @user = current_user
  end

  def edit
    logged_in_user
    if current_user
        @profile = current_user.profile
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
    def concat_str_with_comma(*array_of_str)
        if array_of_str.nil? or array_of_str.length == 0
            return ""
        end
        sanitized_array = array_of_str.compact.split("").flatten
        sanitized_array.join(',')
    end

    def get_array_from_comma_separated_string(str)
        str.strip.split(',')
    end
end

app/views/home/edit.html.erb
 <%= render 'shared/header' %>

<main class="py-10 max-w-7xl mx-auto px-4 sm:px-8">
    <%= form_for(@profile, builder: TailwindInputBuilder) do |f| %>
        <div class="flex justify-end items-center w-full mb-4">
            <div>
                <div>
                   <div>
                 <%= f.submit "Save", class: "flex-shrink-0 px-4 py-2 text-base font-semibold text-white bg-green-600 rounded-lg shadow-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 focus:ring-offset-green-200" %><br/>
                   </div> 
                </div>

            </div>
        </div>

        <%= render 'shared/edit_section', title: "Profile details" do %>
            <%= f.text_field :name, value: @profile.name || current_user.name, placeholder: "Name" %><br/>
            <div class="flex items-center my-4">
                <%= image_tag image_for(current_user), 
                    id: "image-preview", style:"max-width:200px"
                %>
                <div class="flex items-center my-4 px-2">
                <label class="py-2 px-4 flex justify-start items-center bg-blue-600 hover:bg-blue-700 focus:ring-blue-500 focus:ring-offset-blue-200 text-white transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2 rounded-lg mr-4" for = "avatar">
                <img class="mr-2" src="/assets/upload-d20922b4ecce394eca9ef7c397685a1605c948927c6eb8a31d1f6ea8d7284831.svg"> Upload Image
                <%= f.file_field :avatar , accept: "image/*" , type: "file", id: "avatar", name: "profile[avatar]" , class: "hidden" %>
                </label> 
                <br>
            </div>
            </div>
            <%= f.text_field :job_title, value: @profile.job_title, placeholder: "Job title" %><br/>
            <%= f.text_field :total_experience, value: @profile.total_experience, placeholder: "Total experience" %><br/>
            <%= f.text_area :overview, value: @profile.overview, placeholder: "Profile overview", required: true %><br/>
            <p>Career Highlights</p>
            <%= f.text_field :career_highlights, value: concat_str_with_comma(@profile.career_highlights), placeholder: "Career highlights" %>
            <%= render 'shared/multiple_inputs_message' %>
            
            <p>Primary Skills</p>
            <%= f.text_field :primary_skills, value: concat_str_with_comma(@profile.primary_skills), placeholder: "Primary skills" %>
            <%= render 'shared/multiple_inputs_message' %>
            
            <p>Secondary Skills</p>
            <%= f.text_field :secondary_skills, value: concat_str_with_comma(@profile.secondary_skills), placeholder: "Secondary skills" %>
            <%= render 'shared/multiple_inputs_message' %>
            
        <% end %>
        <%= render 'shared/edit_section', title: "Experience" do %>
            <%= f.fields_for :experiences do |experience| %>
                <%= render 'shared/input/experience', experience: experience %>
                <h3 class="text-lg font-semibold">Projects</h3>
                    <div class="pl-4 mb-2 border-l border-blueGray-400">
                        <%= render 'shared/edit_sub_section' do %>
                            <%= experience.fields_for :projects do |project| %>
                            <%= render 'shared/input/project', project: project %>
                        <% end %><br/>
                        <%= render 'shared/input/buttons/add', label: "+ Add Project", path: new_project_path(experience.object.id) %>
                    </div>
                <% end %>
            <% end %><br />
            <%= render 'shared/input/buttons/add', label: "+ Add Experience", path: "/experiences/new" %>
        <% end %>
        <%= render 'shared/edit_section', title: "Education" do %>
            <%= f.fields_for :educations do |education| %>
                <%= render 'shared/input/education', education: education %>
            <% end %><br />
            <%= render 'shared/input/buttons/add', label: "+ Add Education", path: "/educations/new" %>
        <% end %>
        
    <% end %>

</main>

app/views/home/index.html.erb
<%= render 'shared/header' %>
<main class="py-10 max-w-7xl mx-auto px-4 sm:px-8">
    <div class="flex flex-col gap-5 md:flex-row justify-between align-center">
        <div>
        <h1 class="text-3xl"> 
            Namaste, <span class="text-green-600 font-semibold"><%= @user.name %><span>
        </h1>
        </div>
        <div class="flex justify-around md:gap-1">
                <a id="share-btn" onclick="copyText(); this.innerHTML='Copied!'" data-turbolinks="true" class="py-2 px-4 border-2 border-green-600 text-green-600 hover:border-green-700 hover:text-green-700 text-center text-base font-semibold shadow-md hover:shadow-none focus:outline-none rounded-lg" href="#"> Copy Link</a> 
                <a target="_self" data-turbolinks="true" class="py-2 px-4 border-2 border-green-600 text-green-600 hover:border-green-700 hover:text-green-700 text-center text-base font-semibold shadow-md hover:shadow-none focus:outline-none rounded-lg" href="/preview" >Preview</a>
                <a target="_self" data-turbolinks="true" class="py-2 px-4 border-2 border-green-600 text-green-600 hover:border-green-700 hover:text-green-700 text-center text-base font-semibold shadow-md hover:shadow-none focus:outline-none rounded-lg" href="profiles/<%= @user.profile.id %>.pdf" >PDF</a>
                <%= render 'shared/input/buttons/secondary', color: "green", 
                label:"  Edit  ", href: edit_url %>

        </div>
    </div>
    <script>
        function copyText() {
            /* Copy text into clipboard */
            // navigator.clipboard.writeText("resumeflex.herokuapp.com/profiles/<%= @user.profile.id%>");
            copyToClipboard("resumeflex.herokuapp.com/profiles/<%= @user.profile.id %>");
        }
        function copyToClipboard(textToCopy) {
         if (navigator.clipboard && window.isSecureContext) {
                return navigator.clipboard.writeText(textToCopy);
         } else {
                // text area method
                let textArea = document.createElement("textarea");
                textArea.value = textToCopy;
                // make the textarea out of viewport
                textArea.style.position = "fixed";
                textArea.style.left = "-999999px";
                textArea.style.top = "-999999px";
                document.body.appendChild(textArea);
                textArea.focus();
                textArea.select();
                return new Promise((res, rej) => {
                    document.execCommand('copy') ? res() : rej();
                    textArea.remove();
                });
            }
        }
    </script>
    <%= render 'shared/profile/preview', profile: @user.profile%>

</main>